if (typeof Deck === "undefined") { var Deck = []; }

// Inicializa o Objeto do Deck atual
var zombies = {
  Titulo: "Zombies",
  Imagem: "zombies/imgs/bg.png",
  Creditos: "The original horde deck by Peter Knudson (against-the-horde.com)",
  RegrasEspeciais: "Todas as criaturas controladas pela horda possuem Ímpeto.",
  Carta: [],
  Criar: []
};

zombies.Carta.push({ Imagem: "zombies/imgs/zombies_1.png", Url: "https://cards.scryfall.io/display/front/c/7/c7e4fa7f-a5d7-46cd-bc46-d3d231235460.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_1.png", Url: "https://cards.scryfall.io/display/front/c/7/c7e4fa7f-a5d7-46cd-bc46-d3d231235460.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_1.png", Url: "https://cards.scryfall.io/display/front/c/7/c7e4fa7f-a5d7-46cd-bc46-d3d231235460.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_1.png", Url: "https://cards.scryfall.io/display/front/c/7/c7e4fa7f-a5d7-46cd-bc46-d3d231235460.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_2.png", Url: "https://cards.scryfall.io/display/front/8/6/86d5440a-7460-4b4f-a167-a6c4fb2d855e.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_3.png", Url: "https://cards.scryfall.io/display/front/3/7/37c2b228-94c0-4e84-ad6d-80b170bb6c0c.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_4.png", Url: "https://cards.scryfall.io/display/front/3/4/34a27142-cf45-4164-9e10-373e5c8bf7c6.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_5.png", Url: "https://cards.scryfall.io/display/front/f/c/fce2baa4-2976-4bbd-b6c5-a5a3c6a901be.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_6.png", Url: "https://cards.scryfall.io/grid/front/3/b/3b4faa6e-5013-4c59-80f5-662a386672eb.webp", ComecarEmCampo: false, Marco: false, LateGame: true, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_7.png", Url: "https://cards.scryfall.io/display/front/d/1/d17aaa92-10ca-4f70-b45e-5a51e9192efb.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_7.png", Url: "https://cards.scryfall.io/display/front/d/1/d17aaa92-10ca-4f70-b45e-5a51e9192efb.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_8.png", Url: "https://cards.scryfall.io/display/front/c/d/cd2ee72e-68d3-46b9-abc6-08532ce412b2.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_8.png", Url: "https://cards.scryfall.io/display/front/c/d/cd2ee72e-68d3-46b9-abc6-08532ce412b2.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_8.png", Url: "https://cards.scryfall.io/display/front/c/d/cd2ee72e-68d3-46b9-abc6-08532ce412b2.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_9.png", Url: "https://cards.scryfall.io/display/front/c/0/c035ff58-9df3-4db4-b9d0-97d58080ecfe.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_9.png", Url: "https://cards.scryfall.io/display/front/c/0/c035ff58-9df3-4db4-b9d0-97d58080ecfe.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_10.png", Url: "https://cards.scryfall.io/display/front/c/2/c21cbb10-9157-4887-a752-29b9e94fc77a.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_10.png", Url: "https://cards.scryfall.io/display/front/c/2/c21cbb10-9157-4887-a752-29b9e94fc77a.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_11.png", Url: "https://cards.scryfall.io/display/front/8/2/82633f38-5af1-429e-8c9d-db536af85309.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_11.png", Url: "https://cards.scryfall.io/display/front/8/2/82633f38-5af1-429e-8c9d-db536af85309.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_12.png", Url: "https://cards.scryfall.io/display/front/a/7/a7f7927b-64ae-4448-9540-8d7bbe88c9cc.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_13.png", Url: "https://cards.scryfall.io/display/front/4/1/410a214b-09c4-49bd-a461-3330d0249ae5.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_13.png", Url: "https://cards.scryfall.io/display/front/4/1/410a214b-09c4-49bd-a461-3330d0249ae5.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_14.png", Url: "https://cards.scryfall.io/display/front/d/d/dd119aa8-8414-4942-9a28-3e68a9a52a8e.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_15.png", Url: "https://cards.scryfall.io/display/front/0/1/01482b0c-d05b-4356-9144-e044159f4dcb.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_16.png", Url: "https://cards.scryfall.io/display/front/7/c/7c11c11d-9809-4031-8cbc-21aef07d7f1f.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_16.png", Url: "https://cards.scryfall.io/display/front/7/c/7c11c11d-9809-4031-8cbc-21aef07d7f1f.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_17.png", Url: "https://cards.scryfall.io/display/front/0/5/053b59b4-a22c-4228-aadc-ae9da6bb465e.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_18.png", Url: "https://cards.scryfall.io/display/front/3/f/3f2ef91f-d113-4e8d-a164-c6e261aa9c12.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_19.png", Url: "https://cards.scryfall.io/display/front/8/f/8f8a75da-ea3c-43e7-9d32-1c92f8ec0fd2.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: false, Artefato: false, Encantamento: true, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_19.png", Url: "https://cards.scryfall.io/display/front/8/f/8f8a75da-ea3c-43e7-9d32-1c92f8ec0fd2.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: false, Artefato: false, Encantamento: true, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_20.png", Url: "https://cards.scryfall.io/display/front/5/e/5e1324b6-dba0-4aff-a403-a45d2b405f5b.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: false, Artefato: false, Encantamento: true, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_21.png", Url: "https://cards.scryfall.io/display/front/1/5/155ae16c-f32b-421d-a92a-bf13d9f32891.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: false, Artefato: false, Encantamento: true, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_22.png", Url: "https://cards.scryfall.io/display/front/c/9/c9dbfc7c-164d-47b8-8f05-987864fca89b.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: false, Artefato: false, Encantamento: true, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_23.png", Url: "https://cards.scryfall.io/display/front/b/f/bf818314-1eb4-48da-8e6f-ff7b89873b63.webp", ComecarEmCampo: false, Marco: false, LateGame: true, Permanente: false, Criatura: false, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: true, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: true, ExilarAposConjurarDoCemiterio: true });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_24.png", Url: "https://cards.scryfall.io/display/front/d/3/d3c0aac5-b9f1-4446-bfea-3e1dd1cf1f2f.webp", ComecarEmCampo: false, Marco: false, LateGame: true, Permanente: false, Criatura: false, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: true, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_25.png", Url: "https://cards.scryfall.io/display/front/6/4/64b0d9e7-4a0f-4f07-99ae-31c3c9f0037a.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: false, Criatura: false, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: true, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_25.png", Url: "https://cards.scryfall.io/display/front/6/4/64b0d9e7-4a0f-4f07-99ae-31c3c9f0037a.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: false, Criatura: false, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: true, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_26.png", Url: "https://cards.scryfall.io/display/front/7/2/72d21d0d-7de7-4f03-8663-002c9290512f.webp", ComecarEmCampo: false, Marco: false, LateGame: true, Permanente: false, Criatura: false, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: true, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_27.png", Url: "https://cards.scryfall.io/display/front/a/6/a6e04dd2-75ad-4427-93cc-37226340c2fb.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: false, Criatura: false, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: true, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_28.png", Url: "https://cards.scryfall.io/display/front/b/e/be7e26e1-5db6-49ba-a88e-c79d889cd364.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_28.png", Url: "https://cards.scryfall.io/display/front/b/e/be7e26e1-5db6-49ba-a88e-c79d889cd364.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_28.png", Url: "https://cards.scryfall.io/display/front/b/e/be7e26e1-5db6-49ba-a88e-c79d889cd364.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_28.png", Url: "https://cards.scryfall.io/display/front/b/e/be7e26e1-5db6-49ba-a88e-c79d889cd364.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_28.png", Url: "https://cards.scryfall.io/display/front/b/e/be7e26e1-5db6-49ba-a88e-c79d889cd364.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_29.png", Url: "https://cards.scryfall.io/grid/back/4/f/4f153ca0-0e55-4f3c-9780-570708844fd3.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_29.png", Url: "https://cards.scryfall.io/grid/back/4/f/4f153ca0-0e55-4f3c-9780-570708844fd3.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_29.png", Url: "https://cards.scryfall.io/grid/back/4/f/4f153ca0-0e55-4f3c-9780-570708844fd3.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_29.png", Url: "https://cards.scryfall.io/grid/back/4/f/4f153ca0-0e55-4f3c-9780-570708844fd3.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_29.png", Url: "https://cards.scryfall.io/grid/back/4/f/4f153ca0-0e55-4f3c-9780-570708844fd3.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_29.png", Url: "https://cards.scryfall.io/grid/back/4/f/4f153ca0-0e55-4f3c-9780-570708844fd3.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_29.png", Url: "https://cards.scryfall.io/grid/back/4/f/4f153ca0-0e55-4f3c-9780-570708844fd3.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_29.png", Url: "https://cards.scryfall.io/grid/back/4/f/4f153ca0-0e55-4f3c-9780-570708844fd3.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_29.png", Url: "https://cards.scryfall.io/grid/back/4/f/4f153ca0-0e55-4f3c-9780-570708844fd3.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_29.png", Url: "https://cards.scryfall.io/grid/back/4/f/4f153ca0-0e55-4f3c-9780-570708844fd3.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_29.png", Url: "https://cards.scryfall.io/grid/back/4/f/4f153ca0-0e55-4f3c-9780-570708844fd3.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_29.png", Url: "https://cards.scryfall.io/grid/back/4/f/4f153ca0-0e55-4f3c-9780-570708844fd3.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_29.png", Url: "https://cards.scryfall.io/grid/back/4/f/4f153ca0-0e55-4f3c-9780-570708844fd3.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_29.png", Url: "https://cards.scryfall.io/grid/back/4/f/4f153ca0-0e55-4f3c-9780-570708844fd3.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_29.png", Url: "https://cards.scryfall.io/grid/back/4/f/4f153ca0-0e55-4f3c-9780-570708844fd3.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_29.png", Url: "https://cards.scryfall.io/grid/back/4/f/4f153ca0-0e55-4f3c-9780-570708844fd3.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_29.png", Url: "https://cards.scryfall.io/grid/back/4/f/4f153ca0-0e55-4f3c-9780-570708844fd3.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_29.png", Url: "https://cards.scryfall.io/grid/back/4/f/4f153ca0-0e55-4f3c-9780-570708844fd3.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_29.png", Url: "https://cards.scryfall.io/grid/back/4/f/4f153ca0-0e55-4f3c-9780-570708844fd3.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_29.png", Url: "https://cards.scryfall.io/grid/back/4/f/4f153ca0-0e55-4f3c-9780-570708844fd3.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_29.png", Url: "https://cards.scryfall.io/grid/back/4/f/4f153ca0-0e55-4f3c-9780-570708844fd3.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_29.png", Url: "https://cards.scryfall.io/grid/back/4/f/4f153ca0-0e55-4f3c-9780-570708844fd3.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_29.png", Url: "https://cards.scryfall.io/grid/back/4/f/4f153ca0-0e55-4f3c-9780-570708844fd3.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_29.png", Url: "https://cards.scryfall.io/grid/back/4/f/4f153ca0-0e55-4f3c-9780-570708844fd3.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_29.png", Url: "https://cards.scryfall.io/grid/back/4/f/4f153ca0-0e55-4f3c-9780-570708844fd3.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_29.png", Url: "https://cards.scryfall.io/grid/back/4/f/4f153ca0-0e55-4f3c-9780-570708844fd3.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_29.png", Url: "https://cards.scryfall.io/grid/back/4/f/4f153ca0-0e55-4f3c-9780-570708844fd3.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_29.png", Url: "https://cards.scryfall.io/grid/back/4/f/4f153ca0-0e55-4f3c-9780-570708844fd3.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_29.png", Url: "https://cards.scryfall.io/grid/back/4/f/4f153ca0-0e55-4f3c-9780-570708844fd3.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_29.png", Url: "https://cards.scryfall.io/grid/back/4/f/4f153ca0-0e55-4f3c-9780-570708844fd3.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_29.png", Url: "https://cards.scryfall.io/grid/back/4/f/4f153ca0-0e55-4f3c-9780-570708844fd3.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_29.png", Url: "https://cards.scryfall.io/grid/back/4/f/4f153ca0-0e55-4f3c-9780-570708844fd3.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_29.png", Url: "https://cards.scryfall.io/grid/back/4/f/4f153ca0-0e55-4f3c-9780-570708844fd3.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_29.png", Url: "https://cards.scryfall.io/grid/back/4/f/4f153ca0-0e55-4f3c-9780-570708844fd3.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_29.png", Url: "https://cards.scryfall.io/grid/back/4/f/4f153ca0-0e55-4f3c-9780-570708844fd3.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_29.png", Url: "https://cards.scryfall.io/grid/back/4/f/4f153ca0-0e55-4f3c-9780-570708844fd3.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_29.png", Url: "https://cards.scryfall.io/grid/back/4/f/4f153ca0-0e55-4f3c-9780-570708844fd3.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_29.png", Url: "https://cards.scryfall.io/grid/back/4/f/4f153ca0-0e55-4f3c-9780-570708844fd3.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_29.png", Url: "https://cards.scryfall.io/grid/back/4/f/4f153ca0-0e55-4f3c-9780-570708844fd3.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_29.png", Url: "https://cards.scryfall.io/grid/back/4/f/4f153ca0-0e55-4f3c-9780-570708844fd3.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_29.png", Url: "https://cards.scryfall.io/grid/back/4/f/4f153ca0-0e55-4f3c-9780-570708844fd3.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_29.png", Url: "https://cards.scryfall.io/grid/back/4/f/4f153ca0-0e55-4f3c-9780-570708844fd3.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_29.png", Url: "https://cards.scryfall.io/grid/back/4/f/4f153ca0-0e55-4f3c-9780-570708844fd3.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_29.png", Url: "https://cards.scryfall.io/grid/back/4/f/4f153ca0-0e55-4f3c-9780-570708844fd3.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_29.png", Url: "https://cards.scryfall.io/grid/back/4/f/4f153ca0-0e55-4f3c-9780-570708844fd3.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_29.png", Url: "https://cards.scryfall.io/grid/back/4/f/4f153ca0-0e55-4f3c-9780-570708844fd3.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_29.png", Url: "https://cards.scryfall.io/grid/back/4/f/4f153ca0-0e55-4f3c-9780-570708844fd3.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_29.png", Url: "https://cards.scryfall.io/grid/back/4/f/4f153ca0-0e55-4f3c-9780-570708844fd3.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_29.png", Url: "https://cards.scryfall.io/grid/back/4/f/4f153ca0-0e55-4f3c-9780-570708844fd3.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_29.png", Url: "https://cards.scryfall.io/grid/back/4/f/4f153ca0-0e55-4f3c-9780-570708844fd3.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_29.png", Url: "https://cards.scryfall.io/grid/back/4/f/4f153ca0-0e55-4f3c-9780-570708844fd3.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_29.png", Url: "https://cards.scryfall.io/grid/back/4/f/4f153ca0-0e55-4f3c-9780-570708844fd3.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_29.png", Url: "https://cards.scryfall.io/grid/back/4/f/4f153ca0-0e55-4f3c-9780-570708844fd3.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_29.png", Url: "https://cards.scryfall.io/grid/back/4/f/4f153ca0-0e55-4f3c-9780-570708844fd3.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Carta.push({ Imagem: "zombies/imgs/zombies_29.png", Url: "https://cards.scryfall.io/grid/back/4/f/4f153ca0-0e55-4f3c-9780-570708844fd3.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Criar.push({ Imagem: "zombies/imgs/zombies_30.png", Url: "https://cards.scryfall.io/grid/back/4/f/4f153ca0-0e55-4f3c-9780-570708844fd3.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
zombies.Criar.push({ Imagem: "zombies/imgs/zombies_31.png", Url: "https://cards.scryfall.io/display/front/b/e/be7e26e1-5db6-49ba-a88e-c79d889cd364.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });

Deck.push(zombies);
