if (typeof Deck === "undefined") { var Deck = []; }

// Inicializa o Objeto do Deck atual
var humans = {
  Titulo: "Humans",
  Imagem: "humans/imgs/bg.png",
  Creditos: "Uma versão modificada do deck Armies of Men por TenkayCrit (against-the-horde.com).",
  RegrasEspeciais: "Todas as criaturas controladas pela horda possuem Ímpeto, e são humanos em adição aos seus outros tipos. Todas as fichas controladas pela horda são brancas.",
  Carta: [],
  Criar: []
};

humans.Carta.push({ Imagem: "humans/imgs/humans_1.png", Url: "https://cards.scryfall.io/display/front/1/d/1de30c12-2011-495a-be25-f7a46b23e142.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_2.png", Url: "https://cards.scryfall.io/display/front/0/1/01c2337d-1c3c-4c5e-8b06-dc8a8c56164e.webp", ComecarEmCampo: false, Marco: false, LateGame: true, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_3.png", Url: "https://cards.scryfall.io/display/front/1/8/1865ab25-b01a-4e2c-bf19-ffcb0806358f.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_4.png", Url: "https://cards.scryfall.io/display/front/8/e/8e6c4afb-6a94-4519-91c6-9824fed2892c.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: true, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_5.png", Url: "https://cards.scryfall.io/display/front/6/f/6f236f33-f6d2-4b07-a69d-42165670bd45.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_6.png", Url: "https://cards.scryfall.io/display/front/f/c/fc395215-a2ec-49e1-9b1b-f8fcfe73e361.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_7.png", Url: "https://cards.scryfall.io/display/front/a/4/a46d64ec-aca4-428e-bce6-66cd755c8cc3.webp", ComecarEmCampo: false, Marco: false, LateGame: true, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_8.png", Url: "https://cards.scryfall.io/display/front/f/5/f5e43875-ab5e-4233-892d-fc2c5687fae8.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_9.png", Url: "https://cards.scryfall.io/display/front/6/e/6e201980-e220-44dc-beab-ad13c20332bd.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_9.png", Url: "https://cards.scryfall.io/display/front/6/e/6e201980-e220-44dc-beab-ad13c20332bd.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_10.png", Url: "https://cards.scryfall.io/display/front/5/0/50875c99-c5c3-41dd-a0f9-08c98edfebc9.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_11.png", Url: "https://cards.scryfall.io/display/front/8/2/824aa845-0523-4434-8992-bce42f5b2bcb.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_12.png", Url: "https://cards.scryfall.io/display/front/3/e/3e9ad9ce-f862-4663-9a36-caf0844eb416.webp", ComecarEmCampo: false, Marco: false, LateGame: true, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_13.png", Url: "https://cards.scryfall.io/display/front/8/5/854ee15f-bf36-4b80-9717-6e6f02da790e.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_14.png", Url: "https://cards.scryfall.io/display/front/0/6/06e5d76a-0cec-40e0-b694-2b5c8484f6c0.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_15.png", Url: "https://cards.scryfall.io/display/front/1/8/1811b4fa-fed6-46ea-a6de-bb7624a5b1de.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_16.png", Url: "https://cards.scryfall.io/display/front/8/c/8ca58965-1dfa-40ac-b6c8-f957167ff066.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_17.png", Url: "https://cards.scryfall.io/display/front/1/a/1a516bce-3d2d-4e0f-afc7-27be3d88848c.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_18.png", Url: "https://cards.scryfall.io/display/front/6/2/62a78aae-598e-4f2b-a7bc-c3afc1d0d191.webp", ComecarEmCampo: false, Marco: false, LateGame: true, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_19.png", Url: "https://cards.scryfall.io/display/front/0/f/0f002636-1971-468d-b171-7b8147829972.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_20.png", Url: "https://cards.scryfall.io/display/front/5/4/54153b9c-483e-4e5c-a1ab-b1c8a7a657d4.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_21.png", Url: "https://cards.scryfall.io/display/front/a/5/a5bf9336-80d6-4751-9630-1d28e24cc0cf.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_22.png", Url: "https://cards.scryfall.io/display/front/5/d/5d42be5f-a6a7-4699-abf7-9632de6daede.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_23.png", Url: "https://cards.scryfall.io/display/front/5/3/53c84c4d-e6d6-4eac-9d14-5b6cba914c3d.webp", ComecarEmCampo: false, Marco: false, LateGame: true, Permanente: true, Criatura: false, Artefato: false, Encantamento: true, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_24.png", Url: "https://cards.scryfall.io/display/front/f/9/f964c561-96ac-4558-b46e-ba2c472d5807.webp", ComecarEmCampo: false, Marco: false, LateGame: true, Permanente: true, Criatura: false, Artefato: false, Encantamento: true, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_25.png", Url: "https://cards.scryfall.io/display/front/1/7/17d154d3-7ae5-43ff-9978-d974285e2c89.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: false, Artefato: false, Encantamento: true, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_25.png", Url: "https://cards.scryfall.io/display/front/1/7/17d154d3-7ae5-43ff-9978-d974285e2c89.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: false, Artefato: false, Encantamento: true, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_26.png", Url: "https://cards.scryfall.io/display/front/9/e/9e5dc58b-f486-4b9f-9138-33efa31a05e4.webp", ComecarEmCampo: false, Marco: false, LateGame: true, Permanente: true, Criatura: false, Artefato: false, Encantamento: true, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_27.png", Url: "https://cards.scryfall.io/display/front/f/d/fd6609ef-71af-4775-affc-34153700c556.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: false, Criatura: false, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: true, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_27.png", Url: "https://cards.scryfall.io/display/front/f/d/fd6609ef-71af-4775-affc-34153700c556.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: false, Criatura: false, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: true, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_28.png", Url: "https://cards.scryfall.io/display/front/1/0/10744088-b028-43aa-8a77-cd2a430fbfb6.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: false, Criatura: false, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: true, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_29.png", Url: "https://cards.scryfall.io/display/front/1/4/14d60131-8715-477d-8a67-5f1f99a906a8.webp", ComecarEmCampo: false, Marco: false, LateGame: true, Permanente: false, Criatura: false, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: true, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_29.png", Url: "https://cards.scryfall.io/display/front/1/4/14d60131-8715-477d-8a67-5f1f99a906a8.webp", ComecarEmCampo: false, Marco: false, LateGame: true, Permanente: false, Criatura: false, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: true, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_30.png", Url: "https://cards.scryfall.io/display/front/0/c/0c786c28-1085-4b3e-9164-5fa3adfa5010.webp", ComecarEmCampo: false, Marco: false, LateGame: true, Permanente: false, Criatura: false, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: true, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: true, ExilarAposConjurarDoCemiterio: true });
humans.Carta.push({ Imagem: "humans/imgs/humans_31.png", Url: "https://cards.scryfall.io/display/front/5/0/50c1d6ca-7789-46b5-bc89-85cc3915cb85.webp", ComecarEmCampo: false, Marco: false, LateGame: true, Permanente: false, Criatura: false, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: true, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_32.png", Url: "https://cards.scryfall.io/display/front/7/1/71067239-d46f-4201-a91c-6aa4c41fa8b1.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: false, Criatura: false, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: true, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_32.png", Url: "https://cards.scryfall.io/display/front/7/1/71067239-d46f-4201-a91c-6aa4c41fa8b1.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: false, Criatura: false, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: true, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_33.png", Url: "https://cards.scryfall.io/display/front/1/1/11675d8a-cd81-4055-bdbd-2e709e12ba66.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: false, Criatura: false, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: true, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: true, ExilarAposConjurarDoCemiterio: true });
humans.Carta.push({ Imagem: "humans/imgs/humans_34.png", Url: "https://cards.scryfall.io/display/front/5/3/537d2b05-3f52-45d6-8fe3-26282085d0c6.webp", ComecarEmCampo: false, Marco: false, LateGame: true, Permanente: false, Criatura: false, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: true, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_34.png", Url: "https://cards.scryfall.io/display/front/5/3/537d2b05-3f52-45d6-8fe3-26282085d0c6.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: false, Criatura: false, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: true, Ficha: false, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_35.png", Url: "https://cards.scryfall.io/display/front/6/f/6f4f14e3-6c1a-4388-8cc0-04b96baff9f7.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_35.png", Url: "https://cards.scryfall.io/display/front/6/f/6f4f14e3-6c1a-4388-8cc0-04b96baff9f7.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_35.png", Url: "https://cards.scryfall.io/display/front/6/f/6f4f14e3-6c1a-4388-8cc0-04b96baff9f7.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_35.png", Url: "https://cards.scryfall.io/display/front/6/f/6f4f14e3-6c1a-4388-8cc0-04b96baff9f7.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_35.png", Url: "https://cards.scryfall.io/display/front/6/f/6f4f14e3-6c1a-4388-8cc0-04b96baff9f7.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_35.png", Url: "https://cards.scryfall.io/display/front/6/f/6f4f14e3-6c1a-4388-8cc0-04b96baff9f7.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_35.png", Url: "https://cards.scryfall.io/display/front/6/f/6f4f14e3-6c1a-4388-8cc0-04b96baff9f7.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_35.png", Url: "https://cards.scryfall.io/display/front/6/f/6f4f14e3-6c1a-4388-8cc0-04b96baff9f7.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_35.png", Url: "https://cards.scryfall.io/display/front/6/f/6f4f14e3-6c1a-4388-8cc0-04b96baff9f7.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_35.png", Url: "https://cards.scryfall.io/display/front/6/f/6f4f14e3-6c1a-4388-8cc0-04b96baff9f7.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_36.png", Url: "https://cards.scryfall.io/display/front/8/7/87c688e5-e096-4160-951f-269f995a347b.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_36.png", Url: "https://cards.scryfall.io/display/front/8/7/87c688e5-e096-4160-951f-269f995a347b.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_36.png", Url: "https://cards.scryfall.io/display/front/8/7/87c688e5-e096-4160-951f-269f995a347b.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_36.png", Url: "https://cards.scryfall.io/display/front/8/7/87c688e5-e096-4160-951f-269f995a347b.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_36.png", Url: "https://cards.scryfall.io/display/front/8/7/87c688e5-e096-4160-951f-269f995a347b.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_36.png", Url: "https://cards.scryfall.io/display/front/8/7/87c688e5-e096-4160-951f-269f995a347b.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_36.png", Url: "https://cards.scryfall.io/display/front/8/7/87c688e5-e096-4160-951f-269f995a347b.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_36.png", Url: "https://cards.scryfall.io/display/front/8/7/87c688e5-e096-4160-951f-269f995a347b.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_36.png", Url: "https://cards.scryfall.io/display/front/8/7/87c688e5-e096-4160-951f-269f995a347b.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_36.png", Url: "https://cards.scryfall.io/display/front/8/7/87c688e5-e096-4160-951f-269f995a347b.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_36.png", Url: "https://cards.scryfall.io/display/front/8/7/87c688e5-e096-4160-951f-269f995a347b.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_36.png", Url: "https://cards.scryfall.io/display/front/8/7/87c688e5-e096-4160-951f-269f995a347b.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_36.png", Url: "https://cards.scryfall.io/display/front/8/7/87c688e5-e096-4160-951f-269f995a347b.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_36.png", Url: "https://cards.scryfall.io/display/front/8/7/87c688e5-e096-4160-951f-269f995a347b.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_36.png", Url: "https://cards.scryfall.io/display/front/8/7/87c688e5-e096-4160-951f-269f995a347b.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_36.png", Url: "https://cards.scryfall.io/display/front/8/7/87c688e5-e096-4160-951f-269f995a347b.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_36.png", Url: "https://cards.scryfall.io/display/front/8/7/87c688e5-e096-4160-951f-269f995a347b.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_36.png", Url: "https://cards.scryfall.io/display/front/8/7/87c688e5-e096-4160-951f-269f995a347b.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_36.png", Url: "https://cards.scryfall.io/display/front/8/7/87c688e5-e096-4160-951f-269f995a347b.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_36.png", Url: "https://cards.scryfall.io/display/front/8/7/87c688e5-e096-4160-951f-269f995a347b.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_37.png", Url: "https://cards.scryfall.io/display/front/a/0/a0c79cdb-969b-4c3b-8ad0-cbbd359a966b.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_37.png", Url: "https://cards.scryfall.io/display/front/a/0/a0c79cdb-969b-4c3b-8ad0-cbbd359a966b.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_37.png", Url: "https://cards.scryfall.io/display/front/a/0/a0c79cdb-969b-4c3b-8ad0-cbbd359a966b.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_37.png", Url: "https://cards.scryfall.io/display/front/a/0/a0c79cdb-969b-4c3b-8ad0-cbbd359a966b.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_37.png", Url: "https://cards.scryfall.io/display/front/a/0/a0c79cdb-969b-4c3b-8ad0-cbbd359a966b.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_37.png", Url: "https://cards.scryfall.io/display/front/a/0/a0c79cdb-969b-4c3b-8ad0-cbbd359a966b.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_37.png", Url: "https://cards.scryfall.io/display/front/a/0/a0c79cdb-969b-4c3b-8ad0-cbbd359a966b.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_37.png", Url: "https://cards.scryfall.io/display/front/a/0/a0c79cdb-969b-4c3b-8ad0-cbbd359a966b.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_37.png", Url: "https://cards.scryfall.io/display/front/a/0/a0c79cdb-969b-4c3b-8ad0-cbbd359a966b.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_37.png", Url: "https://cards.scryfall.io/display/front/a/0/a0c79cdb-969b-4c3b-8ad0-cbbd359a966b.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_38.png", Url: "https://cards.scryfall.io/display/front/c/4/c459f2ec-2aa3-44f6-999f-b1467dd4e27c.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_38.png", Url: "https://cards.scryfall.io/display/front/c/4/c459f2ec-2aa3-44f6-999f-b1467dd4e27c.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_38.png", Url: "https://cards.scryfall.io/display/front/c/4/c459f2ec-2aa3-44f6-999f-b1467dd4e27c.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_38.png", Url: "https://cards.scryfall.io/display/front/c/4/c459f2ec-2aa3-44f6-999f-b1467dd4e27c.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_38.png", Url: "https://cards.scryfall.io/display/front/c/4/c459f2ec-2aa3-44f6-999f-b1467dd4e27c.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_38.png", Url: "https://cards.scryfall.io/display/front/c/4/c459f2ec-2aa3-44f6-999f-b1467dd4e27c.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_38.png", Url: "https://cards.scryfall.io/display/front/c/4/c459f2ec-2aa3-44f6-999f-b1467dd4e27c.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_38.png", Url: "https://cards.scryfall.io/display/front/c/4/c459f2ec-2aa3-44f6-999f-b1467dd4e27c.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_38.png", Url: "https://cards.scryfall.io/display/front/c/4/c459f2ec-2aa3-44f6-999f-b1467dd4e27c.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_38.png", Url: "https://cards.scryfall.io/display/front/c/4/c459f2ec-2aa3-44f6-999f-b1467dd4e27c.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_39.png", Url: "https://cards.scryfall.io/display/front/8/3/83313791-7d33-42bf-8ee7-05f17f88940a.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_39.png", Url: "https://cards.scryfall.io/display/front/8/3/83313791-7d33-42bf-8ee7-05f17f88940a.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_39.png", Url: "https://cards.scryfall.io/display/front/8/3/83313791-7d33-42bf-8ee7-05f17f88940a.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_39.png", Url: "https://cards.scryfall.io/display/front/8/3/83313791-7d33-42bf-8ee7-05f17f88940a.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_39.png", Url: "https://cards.scryfall.io/display/front/8/3/83313791-7d33-42bf-8ee7-05f17f88940a.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_39.png", Url: "https://cards.scryfall.io/display/front/8/3/83313791-7d33-42bf-8ee7-05f17f88940a.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_39.png", Url: "https://cards.scryfall.io/display/front/8/3/83313791-7d33-42bf-8ee7-05f17f88940a.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_39.png", Url: "https://cards.scryfall.io/display/front/8/3/83313791-7d33-42bf-8ee7-05f17f88940a.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_39.png", Url: "https://cards.scryfall.io/display/front/8/3/83313791-7d33-42bf-8ee7-05f17f88940a.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Carta.push({ Imagem: "humans/imgs/humans_39.png", Url: "https://cards.scryfall.io/display/front/8/3/83313791-7d33-42bf-8ee7-05f17f88940a.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Criar.push({ Imagem: "humans/imgs/humans_40.png", Url: "https://cards.scryfall.io/display/front/6/f/6f4f14e3-6c1a-4388-8cc0-04b96baff9f7.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Criar.push({ Imagem: "humans/imgs/humans_41.png", Url: "https://cards.scryfall.io/display/front/8/7/87c688e5-e096-4160-951f-269f995a347b.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Criar.push({ Imagem: "humans/imgs/humans_42.png", Url: "https://cards.scryfall.io/display/front/a/0/a0c79cdb-969b-4c3b-8ad0-cbbd359a966b.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Criar.push({ Imagem: "humans/imgs/humans_43.png", Url: "https://cards.scryfall.io/display/front/c/4/c459f2ec-2aa3-44f6-999f-b1467dd4e27c.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });
humans.Criar.push({ Imagem: "humans/imgs/humans_44.png", Url: "https://cards.scryfall.io/display/front/8/3/83313791-7d33-42bf-8ee7-05f17f88940a.webp", ComecarEmCampo: false, Marco: false, LateGame: false, Permanente: true, Criatura: true, Artefato: false, Encantamento: false, Terreno: false, Planeswalker: false, Batalha: false, Instantanea: false, Feitico: false, Ficha: true, NaoAtaca: false, ConjurarDoCemiterio: false, ExilarAposConjurarDoCemiterio: false });

Deck.push(humans);
